spring:
  datasource:
    username: root
    password: Pitersql
    url: jdbc:mysql://localhost:3306/item_finder?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8081
